version: '3.7'

services:
  server:
    build: 
      context: ./
      dockerfile: Dockerfile
    image: lotmanager-ui
    container_name: ui-server
    ports:
    - 3000:3000
    volumes:
      - ./.env:/.env
    restart: unless-stopped